# GLOBAL INFORMATION
ACCESS_POINT="ServerRMI"

# CLIENT INFORMATION
APP_NAME="TestApp"

# INFORMATION SENT
SUB_PROTOCOL=$1
OPERAND_1=$2
OPERAND_2=$3

# CLIENT
java $APP_NAME $ACCESS_POINT $SUB_PROTOCOL $OPERAND_1 $OPERAND_2

$SHELL