# GLOBAL INFORMATION
ACCESS_POINT="PeerRMI"

# IPs AND PORTs
MC_MULTICAST_IP="224.0.0.3"
MC_PORT="3333"

MDB_MULTICAST_IP="224.0.0.4"
MDB_PORT="4444"

MDR_MULTICAST_IP="224.0.0.5"
MDR_PORT="5555"

# GET ID OF THE PEER
VERSION_APP=${1:-"1.0"}
PEER_ID=${2:-1}		# Default is set to 1, ${1:-n} to change default to n


java Peer $VERSION_APP $PEER_ID $ACCESS_POINT$PEER_ID $MC_MULTICAST_IP $MC_PORT $MDB_MULTICAST_IP $MDB_PORT $MDR_MULTICAST_IP $MDR_PORT

$SHELL