# GLOBAL INFORMATION
ACCESS_POINT="ServerRMI"

# SERVER INFORMATION
VERSION_APP="1.0"
SERVER_ID="1"

# IPs AND PORTs
MC_MULTICAST_IP="1"
MC_PORT="11"

MDB_MULTICAST_IP="2"
MDB_PORT="22"

MDR_MULTICAST_IP="3"
MDR_PORT="33"

# CLIENT INFORMATION
APP_NAME="TestApp"


# SETUP
start rmiregistry
sleep 1

# SERVER
start java Server $VERSION_APP $SERVER_ID $ACCESS_POINT #$MC_MULTICAST_IP $MC_PORT $MDB_MULTICAST_IP $MDB_PORT $MDR_MULTICAST_IP $MDR_PORT
sleep 1

# CLIENT
java $APP_NAME $ACCESS_POINT BACKUP "ola.txt" 2

$SHELL